version: '3'
services:
  raspi_ros:
    #image: raspi:active
    build: .
    environment:
      # set ROS_MASTER_URI to match with the ros master
      -  ROS_MASTER_URI=http://192.168.1.1:11311
      # set ROS_IP to match with the raspbery's ip in the ros network
      - ROS_IP=192.168.1.2
      # set THIS_RAS_NAME to the name of this raspberry in the netowrk
      - THIS_RAS_NAME='None'
    devices:
      - /dev/mem
    volumes:
      - $HOME/reconcycle_config/:/reconcycle_config
    privileged: true 
    network_mode: "host"
    restart: always

