version: '3'
services:
  ros1_active:
    image: raspi:active
    environment:
      # set ROS_MASTER_URI to match with the ros master
      -  ROS_MASTER_URI=http://10.20.0.1:11311
      # set ROS_IP to match with the raspbery's ip in the ros network
      # - ROS_IP=000.000.000.000
      - THIS_RAS_NAME='None'
    devices:
      - /dev/mem
    volumes:
      - $HOME/reconcycle_config/:/reconcycle_config
    privileged: true 
    network_mode: "host"
    restart: always

